services:
  dsci522_milestone4:
    build:
      context: .
      dockerfile: Dockerfile
    image: dsci522_milestone4:0.1
    volumes:
      - ./data:/workspace/data
      - ./figures:/workspace/figures
      - ./models:/workspace/models
      - ./reports:/workspace/reports
      - ./results:/workspace/results
      - ./scripts:/workspace/scripts
      - ./test:/workspace/test
      - ./Makefile:/workspace/Makefile
    working_dir: /workspace
    stdin_open: true
    tty: true