name: dsci522_milestone1
channels:
  - conda-forge
dependencies:
  - python=3.12.12
  - numpy=2.3.5
  - pandas=2.3.3
  - matplotlib=3.10.8 
  - seaborn=0.13.2 
  - altair=6.0.0 
  - scikit-learn=1.7.2
  - pip=25.3